import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from 'src/styles/Home.module.css';
import Link from 'next/link';
import { getAllPosts } from 'src/hooks/api';
import { PostType } from 'src/types/type';
import { GetStaticProps } from 'next';
import { PostProps } from '../types/type';

const inter = Inter({ subsets: ['latin'] });

// SSG
export async function getStaticProps() {
  const posts: PostType[] = await getAllPosts();

  return {
    props: {
      posts,
    },
  };
}

export default function Home({ posts }: PostProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <h1>Nest.js Blog</h1>
        <ul className={styles.postList}>
          {posts.map((post: PostType) => (
            <li className={styles.post} key={post.id}>
              <h2 className={styles.title}>{post.title}</h2>
              <p className={styles.author}>By {post.author}</p>
            </li>
          ))}
        </ul>
      </div>
    </>
  );
}
